nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: This API is about BileMo Application, if you are logged, you can see all products and add, delete, update users in your user list.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
